import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';

import type { Bridge } from '../bridge.js';
import { fetchCaptions } from '../captions.js';
import { parseTime, formatTime } from '../timeparse.js';
import { parseTranscript, formatTranscript, searchTranscript } from '../transcript.js';
import type { Segment } from '../transcript.js';
import { ok, handler, getPlayerState, resolveVideoParam } from './util.js';

interface CachedTranscript {
  title: string;
  language: string;
  isAutoGenerated: boolean;
  segments: Segment[];
}

// Process-lifetime cache: transcripts don't change, and search/re-reads shouldn't refetch.
const cache = new Map<string, CachedTranscript>();

/**
 * Fetch (or reuse) the transcript of the currently open video. The video id comes
 * from player state, so a `video` param naming anything other than the open video
 * is an error.
 */
async function currentTranscript(
  bridge: Bridge,
  video?: string,
  lang?: string,
): Promise<CachedTranscript> {
  const state = await getPlayerState(bridge);
  if (!state.videoId)
    throw new Error('No YouTube video is open in the managed tab — use open_video first.');
  if (video && video.trim()) {
    const row = await resolveVideoParam(bridge, video);
    if (row.youtube_id !== state.videoId) {
      throw new Error(
        `"${row.title}" is not the currently open video — transcripts are fetched from the open page. Use open_video first.`,
      );
    }
  }
  const key = `${state.videoId}:${lang ?? ''}`;
  const hit = cache.get(key);
  if (hit) return hit;
  const payload = await fetchCaptions(state.videoId, lang);
  const segments = parseTranscript(payload.raw);
  if (segments.length === 0)
    throw new Error('The transcript for this video is empty — it may have no usable captions.');
  const entry: CachedTranscript = {
    title: state.title || state.videoId,
    language: payload.language,
    isAutoGenerated: payload.isAutoGenerated,
    segments,
  };
  cache.set(key, entry);
  return entry;
}

export function registerTranscriptTools(server: McpServer, bridge: Bridge): void {
  server.registerTool(
    'get_transcript',
    {
      description:
        'Get the caption transcript of the currently open video as "[m:ss] text" lines. ' +
        'Long transcripts are truncated — pass start/end to window a range, or use search_transcript to find a topic.',
      inputSchema: {
        start: z.string().optional().describe('Window start, e.g. "1:30" — omit for the beginning'),
        end: z.string().optional().describe('Window end, e.g. "12:00" — omit for the end'),
        lang: z
          .string()
          .optional()
          .describe('Language code like "en" — omit for the default track'),
        video: z
          .string()
          .optional()
          .describe('Saved video title — must match the currently open video'),
      },
    },
    handler(async ({ start, end, lang, video }) => {
      const startS = start === undefined ? undefined : parseTime(start);
      const endS = end === undefined ? undefined : parseTime(end);
      if (startS !== undefined && endS !== undefined && endS <= startS)
        throw new Error(`end (${formatTime(endS)}) must be after start (${formatTime(startS)})`);
      const t = await currentTranscript(bridge, video, lang);
      const header = `Transcript of "${t.title}" (${t.language}${t.isAutoGenerated ? ', auto-generated' : ''}):`;
      return ok(`${header}\n\n${formatTranscript(t.segments, { start: startS, end: endS })}`);
    }),
  );

  server.registerTool(
    'search_transcript',
    {
      description:
        "Search the currently open video's transcript for a word or phrase (case-insensitive). " +
        'Returns matching moments with timestamps and surrounding context — pair with seek to jump to a topic.',
      inputSchema: {
        query: z.string().describe('Word or phrase to find, e.g. "dorian mode"'),
        lang: z
          .string()
          .optional()
          .describe('Language code like "en" — omit for the default track'),
        video: z
          .string()
          .optional()
          .describe('Saved video title — must match the currently open video'),
      },
    },
    handler(async ({ query, lang, video }) => {
      const t = await currentTranscript(bridge, video, lang);
      const matches = searchTranscript(t.segments, query);
      if (matches.length === 0) return ok(`No transcript matches for "${query}" in "${t.title}".`);
      return ok({
        video: t.title,
        matches: matches.map((m) => ({ time: formatTime(m.start), context: m.context })),
      });
    }),
  );
}
